### ISSUE TITLE
Operator does not respect "replicas"

### ISSUE THREAD

**Issue by fhennig** [stackabletech/opa-operator#251]
I noticed that the operator ignores the "replicas" setting on a rolegroup. That is unexpected. I know that it uses a daemonset and that therefore the replicas setting probably doesn't make sense, but maybe we should remove it in that case.

Not very high priority though I believe.

**Comment by maltesander** [comment]
We want one pod per node and therefore the Daemonset. The `replicas` come from the operator-rs `RoleGroup`, so we cannot remove it. Replicas are optional though.

**Comment by fhennig** [comment]
Hmm yes, maybe I'm being too picky here but I don't like that there's a thing I can set in the CR that doesn't actually do anything.

But I see that it comes from the framework and it's not easy to remove it in that specific case.

**Comment by razvan** [comment]
I'm closing this as I don't think users are affected in any way,
