### ISSUE TITLE
Document the BundleBuilder and Rego rule ConfigMaps

### ISSUE THREAD

**Issue by maltesander** [stackabletech/opa-operator#274]
We currently do not explain the concept of the bundle builder (except two sentences in https://docs.stackable.tech/opa/stable/implementation-notes.html).
A Rego config map is shown in the getting started guide but not further explained. This should be better documented (in combination with the bundle builder).

## Acceptance

- [x] Implementation Notes / Concepts are extended to explain the bundle builder
  - [x] Extra Container with a local webserver, reading rego configmaps and providing a bundle.tar requested by the OPA container
  - [x] Pros (and Cons):
    - Pro: Bundles can be dynamically extendend / reduced by adding or removing rego config maps
    - Optional Cons: Depending on the amount of rules, zipping these can lead to high CPU consumption
- [x] Implementation Notes or Concepts are extended to explain the rego config maps
  - [x] Example rego rule configmaps are shown and explainend
  - [x] How this can be extended / dynamically adapted

**Comment by lfrancke** [comment]
Malte believes we have documentation on how to get Regorules in but not about the bundle builder

**Comment by lfrancke** [comment]
None of the boxes have been ticked. Could you check whether all of it has been done? @razvan

**Comment by razvan** [comment]
I took all the acceptance criteria into consideration and I belive I implemented all but with different wording.
