### ISSUE TITLE
Allow configuring OPA log level

### ISSUE THREAD

**Issue by nightkr** [stackabletech/opa-operator#373]
Requested in https://stackable-workspace.slack.com/archives/C02JK31U59R/p1667988811260369

**Comment by fhennig** [comment]
I think we'll properly implement this into the CRD once we have our Logging CRD design fleshed out.

But seeing how this can be set with a commandline flag, maybe we could have commandline argument overrides like we have for envvars and config files?

**Comment by lfrancke** [comment]
@maltesander Will this be part of #410 ?

**Comment by maltesander** [comment]
@lfrancke yes!

**Comment by lfrancke** [comment]
Excellent, thank you!

**Comment by maltesander** [comment]
Done in https://github.com/stackabletech/opa-operator/issues/410
