### ISSUE TITLE
Write ADR on CRD changes for UserInfoFetcher

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/opa-operator#478]

**Comment by NickLarsenNZ** [comment]
An example of the CRD changes in action: https://github.com/stackabletech/opa-operator/blob/d28b17c78549dee4018879e0a701386927bdc424/tests/templates/kuttl/keycloak-user-info/10-install-opa.yaml.j2#L33C1-L45C34

**Comment by lfrancke** [comment]
Whoever picks this up needs to pick @soenkeliebau on what is actually required here and/or for more information.

**Comment by soenkeliebau** [comment]
Basically all I wanted to ensure with this issue is, that we capture the discussions that were had during the design phase for UIF.

I remember there were a lot of points around what needs to be configured, what doesn't etc.

If there were a couple of opinions on how the config might look I'd just like to capture them here. If I am mistaken and it was all consential from the beginnning this can be closed :)
