### ISSUE TITLE
[NEW VERSION] 0.52 to 0.57

### ISSUE THREAD

**Issue by fhennig** [stackabletech/opa-operator#479]
**Which new version of OpenPolicyAgent should we support?**

our current latest version is 0.51, the new latest version is 0.57

**Additional information**

changelog: https://github.com/open-policy-agent/opa/blob/main/CHANGELOG.md

**Changes required**

none

**Implementation checklist**

Please don't change anything in this list.
Not all of these steps are necessary for all versions.

- [ ] Update the Docker image
- [ ] Update documentation to include supported version(s)
- [ ] Update and test getting started guide with updated version(s)
- [ ] Update operator to support the new version (if needed)
- [ ] Update integration tests to test use the new versions (in addition or replacing old versions
- [ ] Update examples to use new versions

**Comment by maltesander** [comment]
0.57.0 added in https://github.com/stackabletech/opa-operator/pull/482
