### ISSUE TITLE
Rego rules are not deleted when the CM is deleted

### ISSUE THREAD

**Issue by razvan** [stackabletech/opa-operator#505]
### Current and expected behavior

When a CM with the label `opa.stackable.tech/bundle: true` is deleted, the associated data should be removed from the OPA bundle.

### Would you like to work on fixing this bug?

None

**Comment by sbernauer** [comment]
Just for the record: According to https://github.com/stackabletech/decisions/issues/11 this will be fixed in opa-bundle-builder v2

**Comment by nightkr** [comment]
Bundle builder v2 is now merged: #577.
