### ISSUE TITLE
Support ActiveDirectory backend for user-info-fetcher

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/opa-operator#524]
**Background**
We currently only support KeyClouk as a backend for the UserInfoFetcher. This allows pull through access to Active Directory in theory, but is an extra component to manage, that can be unneeded, when _everything_ should come from AD anyway.

We should look into supporting Active Directory as a direct backend for the UserInfofetcher.

**Implementation Tasks**
- [ ] https://github.com/stackabletech/opa-operator/pull/622

**Comment by lfrancke** [comment]
Can you please link the docs for this and add a snippet for the release notes?
